import {CorpProductData} from "@ns";

export const EXPORT_STRING = "(IPROD+IINV/10)*(-1)";

export enum CorporationState {
    START = "START",
    PURCHASE = "PURCHASE",
    PRODUCTION = "PRODUCTION",
    EXPORT = "EXPORT",
    SALE = "SALE"
}

export enum IndustryType {
    Water = "Water Utilities",
    Spring = "Spring Water",
    Agriculture = "Agriculture",
    Fishing = "Fishing",
    Mining = "Mining",
    Refinery = "Refinery",
    Restaurant = "Restaurant",
    Tobacco = "Tobacco",
    Chemical = "Chemical",
    Pharmaceutical = "Pharmaceutical",
    Computers = "Computer Hardware",
    Robotics = "Robotics",
    Software = "Software",
    Healthcare = "Healthcare",
    RealEstate = "Real Estate",
}

export enum CorpEmployeeJob {
    Operations = "Operations",
    Engineer = "Engineer",
    Business = "Business",
    Management = "Management",
    RandD = "Research & Development",
    Intern = "Intern",
    Unassigned = "Unassigned",
}

export enum CorpUnlockName {
    Export = "Export",
    SmartSupply = "Smart Supply",
    MarketResearchDemand = "Market Research - Demand",
    MarketDataCompetition = "Market Data - Competition",
    VeChain = "VeChain",
    ShadyAccounting = "Shady Accounting",
    GovernmentPartnership = "Government Partnership",
    WarehouseAPI = "Warehouse API",
    OfficeAPI = "Office API",
}

export enum CorpUpgradeName {
    SmartFactories = "Smart Factories",
    SmartStorage = "Smart Storage",
    DreamSense = "DreamSense",
    WilsonAnalytics = "Wilson Analytics",
    NuoptimalNootropicInjectorImplants = "Nuoptimal Nootropic Injector Implants",
    SpeechProcessorImplants = "Speech Processor Implants",
    NeuralAccelerators = "Neural Accelerators",
    FocusWires = "FocusWires",
    ABCSalesBots = "ABC SalesBots",
    ProjectInsight = "Project Insight",
}

export enum CorpMaterialName {
    Water = "Water",
    Ore = "Ore",
    Minerals = "Minerals",
    Food = "Food",
    Plants = "Plants",
    Metal = "Metal",
    Hardware = "Hardware",
    Chemicals = "Chemicals",
    Drugs = "Drugs",
    Robots = "Robots",
    AiCores = "AI Cores",
    RealEstate = "Real Estate",
}

export enum SmartSupplyOption {
    leftovers = "leftovers",
    imports = "imports",
    none = "none",
}

export enum CorpBaseResearchName  {
    Lab = "Hi-Tech R&D Laboratory",
    AutoBrew = "AutoBrew",
    AutoParty = "AutoPartyManager",
    AutoDrug = "Automatic Drug Administration",
    CPH4Inject = "CPH4 Injections",
    Drones = "Drones",
    DronesAssembly = "Drones - Assembly",
    DronesTransport = "Drones - Transport",
    GoJuice = "Go-Juice",
    RecruitHR = "HRBuddy-Recruitment",
    TrainingHR = "HRBuddy-Training",
    MarketTa1 = "Market-TA.I",
    MarketTa2 = "Market-TA.II",
    Overclock = "Overclock",
    SelfCorrectAssemblers = "Self-Correcting Assemblers",
    Stimu = "Sti.mu",
}

export enum CorpProductResearchName {
    Capacity1 = "uPgrade: Capacity.I",
    Capacity2 = "uPgrade: Capacity.II",
    Dashboard = "uPgrade: Dashboard",
    Fulcrum = "uPgrade: Fulcrum",
}

export const CorpResearchName = { ...CorpProductResearchName, ...CorpBaseResearchName };

export enum CreatingCorporationCheckResult {
    Success = "Success",
    NoSf3OrDisabled = "NoSf3OrDisabled",
    CorporationExists = "CorporationExists",
    UseSeedMoneyOutsideBN3 = "UseSeedMoneyOutsideBN3",
    DisabledBySoftCap = "DisabledBySoftCap",
}


export interface CorpIndustryData {
    name: IndustryType;
    startingCost: number;
    description: string;
    product?: CorpProductData;
    recommendStarting: boolean;
    requiredMaterials: Partial<Record<CorpMaterialName, number>>;
    realEstateFactor?: number;
    scienceFactor?: number;
    hardwareFactor?: number;
    robotFactor?: number;
    aiCoreFactor?: number;
    storageScaleFactor: number;
    advertisingFactor?: number;
    producedMaterials?: CorpMaterialName[];
    makesMaterials: boolean;
    makesProducts: boolean;
}

export const IndustriesData: Record<IndustryType, CorpIndustryData> = {
    [IndustryType.Agriculture]: {
        name: IndustryType.Agriculture,
        startingCost: 40e9,
        description: "Cultivate crops and breed livestock to produce food.",
        recommendStarting: true,
        realEstateFactor: 0.72,
        scienceFactor: 0.5,
        hardwareFactor: 0.2,
        robotFactor: 0.3,
        aiCoreFactor: 0.3,
        storageScaleFactor: 0.8,
        advertisingFactor: 0.04,
        requiredMaterials: { [CorpMaterialName.Water]: 0.5, [CorpMaterialName.Chemicals]: 0.2 },
        producedMaterials: [CorpMaterialName.Plants, CorpMaterialName.Food],
        makesMaterials: true,
        makesProducts: false,
    },
    [IndustryType.Spring]: {
        name: IndustryType.Spring,
        startingCost: 10e9,
        description: "Gather water through passive means.",
        recommendStarting: false,
        realEstateFactor: 0.2,
        scienceFactor: 0.1,
        hardwareFactor: 0.0,
        robotFactor: 0.0,
        aiCoreFactor: 0.1,
        advertisingFactor: 0.03,
        storageScaleFactor: 1,
        requiredMaterials: {},
        producedMaterials: [CorpMaterialName.Water],
        makesMaterials: true,
        makesProducts: false,
    },
    [IndustryType.Refinery]: {
        name: IndustryType.Refinery,
        startingCost: 50e9,
        description: "Refine ore into usable metal.",
        recommendStarting: true,
        realEstateFactor: 0.3,
        scienceFactor: 0.5,
        hardwareFactor: 0.5,
        robotFactor: 0.4,
        aiCoreFactor: 0.3,
        storageScaleFactor: 1.5,
        advertisingFactor: 0.04,
        requiredMaterials: { [CorpMaterialName.Ore]: 1 },
        producedMaterials: [CorpMaterialName.Metal],
        makesMaterials: true,
        makesProducts: false,
    },
    [IndustryType.Chemical]: {
        name: IndustryType.Chemical,
        startingCost: 70e9,
        description: "Produce industrial chemicals.",
        recommendStarting: false,
        realEstateFactor: 0.25,
        scienceFactor: 0.75,
        hardwareFactor: 0.2,
        robotFactor: 0.25,
        aiCoreFactor: 0.2,
        storageScaleFactor: 1.5,
        advertisingFactor: 0.07,
        requiredMaterials: { [CorpMaterialName.Plants]: 1, [CorpMaterialName.Water]: 0.5 },
        producedMaterials: [CorpMaterialName.Chemicals],
        makesMaterials: true,
        makesProducts: false,
    },
    [IndustryType.Computers]: {
        name: IndustryType.Computers,
        startingCost: 500e9,
        description: "Develop and manufacture new computer hardware and networking infrastructures.",
        product: {
            name: "Product",
            verb: "Create",
            desc: "Design and manufacture a new computer hardware product!",
            ratingWeights: {
                quality: 0.15,
                performance: 0.25,
                durability: 0.25,
                reliability: 0.2,
                aesthetics: 0.05,
                features: 0.1,
            },
        },
        recommendStarting: false,
        realEstateFactor: 0.2,
        scienceFactor: 0.62,
        robotFactor: 0.36,
        aiCoreFactor: 0.19,
        advertisingFactor: 0.17,
        storageScaleFactor: 2,
        requiredMaterials: { [CorpMaterialName.Metal]: 2 },
        producedMaterials: [CorpMaterialName.Hardware],
        makesMaterials: true,
        makesProducts: true,
    },
    [IndustryType.Fishing]: {
        name: IndustryType.Fishing,
        startingCost: 80e9,
        description: "Produce food through the breeding and processing of fish and fish products.",
        recommendStarting: false,
        realEstateFactor: 0.15,
        scienceFactor: 0.35,
        hardwareFactor: 0.35,
        robotFactor: 0.5,
        aiCoreFactor: 0.2,
        storageScaleFactor: 1.15,
        advertisingFactor: 0.08,
        requiredMaterials: { [CorpMaterialName.Plants]: 0.5 },
        producedMaterials: [CorpMaterialName.Food],
        makesMaterials: true,
        makesProducts: false,
    },
    [IndustryType.Restaurant]: {
        name: IndustryType.Restaurant,
        startingCost: 10e9,
        description: "Create your own restaurants all around the world.",
        product: {
            name: "Restaurant",
            verb: "Build",
            desc: "Build and manage a new restaurant!",
            ratingWeights: {
                quality: 0.7,
                durability: 0.1,
                aesthetics: 0.2,
            },
        },
        recommendStarting: true,
        scienceFactor: 0.12,
        hardwareFactor: 0.15,
        robotFactor: 0.3,
        aiCoreFactor: 0.25,
        advertisingFactor: 0.25,
        realEstateFactor: 0.05,
        storageScaleFactor: 1.15,
        requiredMaterials: { [CorpMaterialName.Food]: 0.5, [CorpMaterialName.Water]: 0.5 },
        makesMaterials: false,
        makesProducts: true,
    },
    [IndustryType.Healthcare]: {
        name: IndustryType.Healthcare,
        startingCost: 750e9,
        description: "Create and manage hospitals.",
        product: {
            name: "Hospital",
            verb: "Build",
            desc: "Build and manage a new hospital!",
            ratingWeights: {
                quality: 0.4,
                performance: 0.1,
                durability: 0.1,
                reliability: 0.3,
                features: 0.1,
            },
        },
        recommendStarting: false,
        realEstateFactor: 0.1,
        scienceFactor: 0.75,
        advertisingFactor: 0.11,
        hardwareFactor: 0.1,
        robotFactor: 0.1,
        aiCoreFactor: 0.1,
        storageScaleFactor: 2,
        requiredMaterials: { [CorpMaterialName.Robots]: 10, [CorpMaterialName.AiCores]: 5, [CorpMaterialName.Drugs]: 5, [CorpMaterialName.Food]: 5 },
        makesMaterials: false,
        makesProducts: true,
    },
    [IndustryType.Mining]: {
        name: IndustryType.Mining,
        startingCost: 300e9,
        description: "Extract and process metals from the earth.",
        recommendStarting: false,
        realEstateFactor: 0.3,
        scienceFactor: 0.26,
        hardwareFactor: 0.4,
        robotFactor: 0.45,
        aiCoreFactor: 0.45,
        advertisingFactor: 0.06,
        storageScaleFactor: 1.05,
        requiredMaterials: { [CorpMaterialName.Hardware]: 0.1 },
        producedMaterials: [CorpMaterialName.Ore, CorpMaterialName.Minerals],
        makesMaterials: true,
        makesProducts: false,
    },
    [IndustryType.Pharmaceutical]: {
        name: IndustryType.Pharmaceutical,
        startingCost: 200e9,
        description: "Discover, develop, and create new pharmaceutical drugs.",
        product: {
            name: "Drug",
            verb: "Develop",
            desc: "Design and develop a new pharmaceutical drug!",
            ratingWeights: {
                quality: 0.2,
                performance: 0.2,
                durability: 0.1,
                reliability: 0.3,
                features: 0.2,
            },
        },
        recommendStarting: false,
        realEstateFactor: 0.05,
        scienceFactor: 0.8,
        hardwareFactor: 0.15,
        robotFactor: 0.25,
        aiCoreFactor: 0.2,
        advertisingFactor: 0.16,
        storageScaleFactor: 2,
        requiredMaterials: { [CorpMaterialName.Chemicals]: 2, [CorpMaterialName.Water]: 0.5 },
        producedMaterials: [CorpMaterialName.Drugs],
        makesMaterials: true,
        makesProducts: true,
    },
    [IndustryType.RealEstate]: {
        name: IndustryType.RealEstate,
        startingCost: 600e9,
        description: "Develop and manage real estate properties.",
        product: {
            name: "Property",
            verb: "Develop",
            desc: "Develop a new piece of real estate property!",
            ratingWeights: {
                quality: 0.2,
                durability: 0.25,
                reliability: 0.1,
                aesthetics: 0.35,
                features: 0.1,
            },
        },
        recommendStarting: false,
        robotFactor: 0.6,
        aiCoreFactor: 0.6,
        advertisingFactor: 0.25,
        scienceFactor: 0.05,
        hardwareFactor: 0.05,
        storageScaleFactor: 2,
        requiredMaterials: { [CorpMaterialName.Metal]: 5, [CorpMaterialName.Plants]: 1, [CorpMaterialName.Water]: 2, [CorpMaterialName.Hardware]: 4 },
        producedMaterials: [CorpMaterialName.RealEstate],
        makesMaterials: true,
        makesProducts: true,
    },
    [IndustryType.Robotics]: {
        name: IndustryType.Robotics,
        startingCost: 1e12,
        description: "Develop and create robots.",
        product: {
            name: "Robot",
            verb: "Design",
            desc: "Design and create a new robot or robotic system!",
            ratingWeights: {
                quality: 0.1,
                performance: 0.2,
                durability: 0.2,
                reliability: 0.2,
                aesthetics: 0.1,
                features: 0.2,
            },
        },
        recommendStarting: false,
        realEstateFactor: 0.32,
        scienceFactor: 0.65,
        aiCoreFactor: 0.36,
        advertisingFactor: 0.18,
        hardwareFactor: 0.19,
        storageScaleFactor: 2,
        requiredMaterials: { [CorpMaterialName.Hardware]: 5, [CorpMaterialName.AiCores]: 3 },
        producedMaterials: [CorpMaterialName.Robots],
        makesMaterials: true,
        makesProducts: true,
    },
    [IndustryType.Software]: {
        name: IndustryType.Software,
        startingCost: 25e9,
        description: "Develop computer software and create AI Cores.",
        product: {
            name: "Software",
            verb: "Develop",
            desc: "Develop a new piece of software!",
            ratingWeights: {
                quality: 0.2,
                performance: 0.2,
                reliability: 0.2,
                durability: 0.2,
                features: 0.2,
            },
        },
        recommendStarting: false,
        scienceFactor: 0.62,
        advertisingFactor: 0.16,
        hardwareFactor: 0.25,
        realEstateFactor: 0.15,
        aiCoreFactor: 0.18,
        robotFactor: 0.05,
        storageScaleFactor: 1.15,
        requiredMaterials: { [CorpMaterialName.Hardware]: 0.5 },
        producedMaterials: [CorpMaterialName.AiCores],
        makesMaterials: true,
        makesProducts: true,
    },
    [IndustryType.Tobacco]: {
        name: IndustryType.Tobacco,
        startingCost: 20e9,
        description: "Create and distribute tobacco and tobacco-related products.",
        product: {
            name: "Product",
            verb: "Create",
            desc: "Create a new tobacco product!",
            ratingWeights: {
                quality: 0.7,
                durability: 0.1,
                aesthetics: 0.2,
            },
        },
        recommendStarting: true,
        realEstateFactor: 0.15,
        scienceFactor: 0.75,
        hardwareFactor: 0.15,
        robotFactor: 0.2,
        aiCoreFactor: 0.15,
        advertisingFactor: 0.2,
        storageScaleFactor: 2,
        requiredMaterials: { [CorpMaterialName.Plants]: 1 },
        makesMaterials: false,
        makesProducts: true,
    },
    [IndustryType.Water]: {
        name: IndustryType.Water,
        startingCost: 150e9,
        description: "Distribute water and provide wastewater services.",
        recommendStarting: false,
        realEstateFactor: 0.5,
        scienceFactor: 0.6,
        robotFactor: 0.4,
        aiCoreFactor: 0.4,
        advertisingFactor: 0.08,
        storageScaleFactor: 1.05,
        requiredMaterials: { [CorpMaterialName.Hardware]: 0.1 },
        producedMaterials: [CorpMaterialName.Water],
        makesMaterials: true,
        makesProducts: false,
    },
};

interface CorpMaterialConstantData {
    name: string;
    size: number;
    demandBase: number;
    demandRange: [min: number, max: number];
    competitionBase: number;
    competitionRange: [min: number, max: number];
    baseCost: number;
    maxVolatility: number;
    baseMarkup: number;
}

export const MaterialInfo: Record<CorpMaterialName, CorpMaterialConstantData> = {
    [CorpMaterialName.Water]: {
        name: CorpMaterialName.Water,
        size: 0.05,
        demandBase: 75,
        demandRange: [65, 85],
        competitionBase: 50,
        competitionRange: [40, 60],
        baseCost: 1500,
        maxVolatility: 0.2,
        baseMarkup: 6,
    },
    [CorpMaterialName.Ore]: {
        name: CorpMaterialName.Ore,
        size: 0.01,
        demandBase: 50,
        demandRange: [40, 60],
        competitionBase: 80,
        competitionRange: [65, 95],
        baseCost: 500,
        maxVolatility: 0.2,
        baseMarkup: 6,
    },
    [CorpMaterialName.Minerals]: {
        name: CorpMaterialName.Minerals,
        size: 0.04,
        demandBase: 75,
        demandRange: [60, 90],
        competitionBase: 80,
        competitionRange: [65, 95],
        baseCost: 500,
        maxVolatility: 0.2,
        baseMarkup: 6,
    },
    [CorpMaterialName.Food]: {
        name: CorpMaterialName.Food,
        size: 0.03,
        demandBase: 80,
        demandRange: [70, 90],
        competitionBase: 60,
        competitionRange: [35, 85],
        baseCost: 5000,
        maxVolatility: 1,
        baseMarkup: 3,
    },
    [CorpMaterialName.Plants]: {
        name: CorpMaterialName.Plants,
        size: 0.05,
        demandBase: 70,
        demandRange: [20, 90],
        competitionBase: 50,
        competitionRange: [30, 70],
        baseCost: 3000,
        maxVolatility: 0.6,
        baseMarkup: 3.75,
    },
    [CorpMaterialName.Metal]: {
        name: CorpMaterialName.Metal,
        size: 0.1,
        demandBase: 80,
        demandRange: [75, 85],
        competitionBase: 70,
        competitionRange: [60, 80],
        baseCost: 2650,
        maxVolatility: 1,
        baseMarkup: 6,
    },
    [CorpMaterialName.Hardware]: {
        name: CorpMaterialName.Hardware,
        size: 0.06,
        demandBase: 85,
        demandRange: [80, 90],
        competitionBase: 80,
        competitionRange: [65, 95],
        baseCost: 8e3,
        maxVolatility: 0.5,
        baseMarkup: 1,
    },
    [CorpMaterialName.Chemicals]: {
        name: CorpMaterialName.Chemicals,
        size: 0.05,
        demandBase: 55,
        demandRange: [40, 70],
        competitionBase: 60,
        competitionRange: [40, 80],
        baseCost: 9e3,
        maxVolatility: 1.2,
        baseMarkup: 2,
    },
    [CorpMaterialName.Drugs]: {
        name: CorpMaterialName.Drugs,
        size: 0.02,
        demandBase: 60,
        demandRange: [45, 75],
        competitionBase: 70,
        competitionRange: [40, 99],
        baseCost: 40e3,
        maxVolatility: 1.6,
        baseMarkup: 1,
    },
    [CorpMaterialName.Robots]: {
        name: CorpMaterialName.Robots,
        size: 0.5,
        demandBase: 90,
        demandRange: [80, 99],
        competitionBase: 90,
        competitionRange: [80, 99],
        baseCost: 75e3,
        maxVolatility: 0.5,
        baseMarkup: 1,
    },
    [CorpMaterialName.AiCores]: {
        name: CorpMaterialName.AiCores,
        size: 0.1,
        demandBase: 90,
        demandRange: [80, 99],
        competitionBase: 90,
        competitionRange: [80, 99],
        baseCost: 15e3,
        maxVolatility: 0.8,
        baseMarkup: 0.5,
    },
    [CorpMaterialName.RealEstate]: {
        name: CorpMaterialName.RealEstate,
        size: 0.005,
        demandBase: 50,
        demandRange: [5, 99],
        competitionBase: 50,
        competitionRange: [25, 75],
        baseCost: 80e3,
        maxVolatility: 1.5,
        baseMarkup: 1.5,
    },
};