export interface BitNodeMultipliers {
    AgilityLevelMultiplier: number;
    AugmentationMoneyCost: number;
    AugmentationRepCost: number;
    BladeburnerRank: number;
    BladeburnerSkillCost: number;
    CharismaLevelMultiplier: number;
    ClassGymExpGain: number;
    CodingContractMoney: number;
    CompanyWorkExpGain: number;
    CompanyWorkMoney: number;
    CompanyWorkRepGain: number;
    CorporationDivisions: number;
    CorporationSoftcap: number;
    CorporationValuation: number;
    CrimeExpGain: number;
    CrimeMoney: number;
    CrimeSuccessRate: number;
    DaedalusAugsRequirement: number;
    DefenseLevelMultiplier: number;
    DexterityLevelMultiplier: number;
    FactionPassiveRepGain: number;
    FactionWorkExpGain: number;
    FactionWorkRepGain: number;
    FourSigmaMarketDataApiCost: number;
    FourSigmaMarketDataCost: number;
    GangSoftcap: number;
    GangUniqueAugs: number;
    GoPower: number;
    HackExpGain: number;
    HackingLevelMultiplier: number;
    HackingSpeedMultiplier: number;
    HacknetNodeMoney: number;
    HomeComputerRamCost: number;
    InfiltrationMoney: number;
    InfiltrationRep: number;
    ManualHackMoney: number;
    PurchasedServerCost: number;
    PurchasedServerSoftcap: number;
    PurchasedServerLimit: number;
    PurchasedServerMaxRam: number;
    RepToDonateToFaction: number;
    ScriptHackMoney: number;
    ScriptHackMoneyGain: number;
    ServerGrowthRate: number;
    ServerMaxMoney: number;
    ServerStartingMoney: number;
    ServerStartingSecurity: number;
    ServerWeakenRate: number;
    StrengthLevelMultiplier: number;
    StaneksGiftPowerMultiplier: number;
    StaneksGiftExtraSize: number;
    WorldDaemonDifficulty: number;
}

export const DefaultMultipliers: BitNodeMultipliers = {
    AgilityLevelMultiplier: 1,
    AugmentationMoneyCost: 1,
    AugmentationRepCost: 1,
    BladeburnerRank: 1,
    BladeburnerSkillCost: 1,
    CharismaLevelMultiplier: 1,
    ClassGymExpGain: 1,
    CodingContractMoney: 1,
    CompanyWorkExpGain: 1,
    CompanyWorkMoney: 1,
    CompanyWorkRepGain: 1,
    CorporationDivisions: 1,
    CorporationSoftcap: 1,
    CorporationValuation: 1,
    CrimeExpGain: 1,
    CrimeMoney: 1,
    CrimeSuccessRate: 1,
    DaedalusAugsRequirement: 30,
    DefenseLevelMultiplier: 1,
    DexterityLevelMultiplier: 1,
    FactionPassiveRepGain: 1,
    FactionWorkExpGain: 1,
    FactionWorkRepGain: 1,
    FourSigmaMarketDataApiCost: 1,
    FourSigmaMarketDataCost: 1,
    GangSoftcap: 1,
    GangUniqueAugs: 1,
    GoPower: 1,
    HackExpGain: 1,
    HackingLevelMultiplier: 1,
    HackingSpeedMultiplier: 1,
    HacknetNodeMoney: 1,
    HomeComputerRamCost: 1,
    InfiltrationMoney: 1,
    InfiltrationRep: 1,
    ManualHackMoney: 1,
    PurchasedServerCost: 1,
    PurchasedServerSoftcap: 1,
    PurchasedServerLimit: 1,
    PurchasedServerMaxRam: 1,
    RepToDonateToFaction: 1,
    ScriptHackMoney: 1,
    ScriptHackMoneyGain: 1,
    ServerGrowthRate: 1,
    ServerMaxMoney: 1,
    ServerStartingMoney: 1,
    ServerStartingSecurity: 1,
    ServerWeakenRate: 1,
    StrengthLevelMultiplier: 1,
    StaneksGiftPowerMultiplier: 1,
    StaneksGiftExtraSize: 0,
    WorldDaemonDifficulty: 1
};